<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Endure.Data\Endure.Data.csproj" />
    <ProjectReference Include="..\Endure.Dispatcher\Endure.Dispatcher.csproj" />
  </ItemGroup>

</Project>
