name: Endure

services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: endure
      POSTGRES_USER: endure
      POSTGRES_PASSWORD: endure
    volumes:
      - postgres:/var/lib/postgresql/18/docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U endure -d endure -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
 
  pgadmin:
    image: dpage/pgadmin4:9
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: passw0rd
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
  
  rabbitmq:
    image: rabbitmq:4.2.5
    environment:
      RABBITMQ_DEFAULT_USER: endure
      RABBITMQ_DEFAULT_PASS: endure
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq
      - rabbitmq-log:/var/log/rabbitmq
    ports:
      - "5672:5672"     # AMQP protocol
      - "15672:15672"   # Management UI
      - "1883:1883"     # MQTTS protocol

  # authentik_server:
  #     image: authentik/server:2026.2.1
  #     container_name: authentik_server
  #     command: server
  #     restart: unless-stopped
  #     depends_on:
  #         postgres:
  #             condition: service_healthy
  #     environment:
  #         AUTHENTIK_POSTGRESQL__HOST: postgres
  #         AUTHENTIK_POSTGRESQL__NAME: authentik
  #         AUTHENTIK_POSTGRESQL__PASSWORD: authentik
  #         AUTHENTIK_POSTGRESQL__USER: authentik
  #         AUTHENTIK_SECRET_KEY: very-secret-key
  #     ports:
  #         - "9000:9000"
  #         - "9443:9443"
  #     volumes:
  #         - authentik_data:/data
  #         - authentik_custom_temp:/templates
  #     shm_size: 512mb

  # authentik_worker:
  #     image: authentik/server:2026.2.1
  #     container_name: authentik_worker
  #     command: worker
  #     restart: unless-stopped
  #     depends_on:
  #         postgres:
  #             condition: service_healthy
  #     environment:
  #         AUTHENTIK_POSTGRESQL__HOST: postgres
  #         AUTHENTIK_POSTGRESQL__NAME: authentik
  #         AUTHENTIK_POSTGRESQL__PASSWORD: authentik
  #         AUTHENTIK_POSTGRESQL__USER: authentik
  #         AUTHENTIK_SECRET_KEY: very-secret-key
  #     volumes:
  #         - /var/run/docker.sock:/var/run/docker.sock
  #         - authentik_data:/data
  #         - authentik_certs:/certs
  #         - authentik_custom_temp:/templates
  #     shm_size: 512mb
  #     user: root
     
configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management,rabbitmq_mqtt]."  

volumes:
  postgres:
  pgadmin:
  rabbitmq-lib:
  rabbitmq-log:
  
  authentik_data:
  authentik_certs:
  authentik_custom_temp: