// <auto-generated />
using System;
using Endure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Endure.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260413191722_test")]
    partial class test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Endure.Data.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Log")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LogLevel")
                        .HasColumnType("integer");

                    b.Property<string>("RequestId")
                        .HasColumnType("text");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("bigint");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("Endure.Data.Models.ClimateDevice", b =>
                {
                    b.Property<Guid>("WareHouseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsConnected")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<long>("LastReceived")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("SetHumidity")
                        .HasColumnType("double precision");

                    b.Property<double>("SetTemperature")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("StorageUnitId")
                        .HasColumnType("uuid");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("bigint");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("WareHouseId", "Id");

                    b.HasIndex("WareHouseId", "StorageUnitId");

                    b.ToTable("ClimateDevice");
                });

            modelBuilder.Entity("Endure.Data.Models.ClimateTelemetry", b =>
                {
                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClimateDeviceId")
                        .HasColumnType("uuid");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<double>("Humidity")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<double>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("bigint");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("WarehouseId", "Id");

                    b.ToTable("ClimateTelemetry");
                });

            modelBuilder.Entity("Endure.Data.Models.Product", b =>
                {
                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("uuid");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EAN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("bigint");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("WarehouseId", "Id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Endure.Data.Models.ProductBatch", b =>
                {
                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("BestBefore")
                        .HasColumnType("bigint");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StorageUnitId")
                        .HasColumnType("uuid");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("bigint");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("WarehouseId", "Id");

                    b.HasIndex("WarehouseId", "ProductId");

                    b.HasIndex("WarehouseId", "StorageUnitId");

                    b.ToTable("ProductBatch");
                });

            modelBuilder.Entity("Endure.Data.Models.StorageUnit", b =>
                {
                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSlot")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ShortName")
                        .HasColumnType("text");

                    b.Property<int>("StorageType")
                        .HasColumnType("integer");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("bigint");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("WarehouseId", "Id");

                    b.HasIndex("WarehouseId", "ParentId");

                    b.ToTable("StorageUnit");
                });

            modelBuilder.Entity("Endure.Data.Models.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRoot")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ShortName")
                        .HasColumnType("text");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("bigint");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("Warehouse");
                });

            modelBuilder.Entity("Endure.Data.Models.AuditLog", b =>
                {
                    b.HasOne("Endure.Data.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Endure.Data.Models.ClimateDevice", b =>
                {
                    b.HasOne("Endure.Data.Models.StorageUnit", "StorageUnit")
                        .WithMany("ClimateDevices")
                        .HasForeignKey("WareHouseId", "StorageUnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("StorageUnit");
                });

            modelBuilder.Entity("Endure.Data.Models.ClimateTelemetry", b =>
                {
                    b.HasOne("Endure.Data.Models.ClimateDevice", "ClimateDevice")
                        .WithMany("ClimateTelemetry")
                        .HasForeignKey("WarehouseId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClimateDevice");
                });

            modelBuilder.Entity("Endure.Data.Models.ProductBatch", b =>
                {
                    b.HasOne("Endure.Data.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Endure.Data.Models.Product", "Product")
                        .WithMany("ProductBatches")
                        .HasForeignKey("WarehouseId", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Endure.Data.Models.StorageUnit", "StorageUnit")
                        .WithMany("Products")
                        .HasForeignKey("WarehouseId", "StorageUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("StorageUnit");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Endure.Data.Models.StorageUnit", b =>
                {
                    b.HasOne("Endure.Data.Models.Warehouse", "Warehouse")
                        .WithMany("StorageUnits")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Endure.Data.Models.StorageUnit", "ParentStorageUnit")
                        .WithMany("ChildStorageUnits")
                        .HasForeignKey("WarehouseId", "ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentStorageUnit");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Endure.Data.Models.ClimateDevice", b =>
                {
                    b.Navigation("ClimateTelemetry");
                });

            modelBuilder.Entity("Endure.Data.Models.Product", b =>
                {
                    b.Navigation("ProductBatches");
                });

            modelBuilder.Entity("Endure.Data.Models.StorageUnit", b =>
                {
                    b.Navigation("ChildStorageUnits");

                    b.Navigation("ClimateDevices");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Endure.Data.Models.Warehouse", b =>
                {
                    b.Navigation("StorageUnits");
                });
#pragma warning restore 612, 618
        }
    }
}
