// <auto-generated />
using Endure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Endure.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260331105854_Added_Init_Seed")]
    partial class Added_Init_Seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Endure.Data.Models.ClimateDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsConnected")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<long>("LastReceived")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("StorageUnitId")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StorageUnitId");

                    b.ToTable("ClimateDevice");
                });

            modelBuilder.Entity("Endure.Data.Models.ClimateTelemetry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClimateDeviceId")
                        .HasColumnType("integer");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<double>("Humidity")
                        .HasColumnType("double precision");

                    b.Property<int>("StorageUnitId")
                        .HasColumnType("integer");

                    b.Property<double>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClimateDeviceId");

                    b.ToTable("ClimateTelemetry");
                });

            modelBuilder.Entity("Endure.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Endure.Data.Models.ProductBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("BestBefore")
                        .HasColumnType("bigint");

                    b.Property<long>("Count")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<long>("LastUpdatedAt")
                        .HasColumnType("bigint");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("StorageUnitId")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("StorageUnitId");

                    b.ToTable("ProductBatch");
                });

            modelBuilder.Entity("Endure.Data.Models.StorageUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsSlot")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentStorageUnitId")
                        .HasColumnType("integer");

                    b.Property<string>("ShortName")
                        .HasColumnType("text");

                    b.Property<int>("StorageType")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentStorageUnitId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("StorageUnit");
                });

            modelBuilder.Entity("Endure.Data.Models.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentWarehouseId")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ParentWarehouseId");

                    b.ToTable("Warehouse");
                });

            modelBuilder.Entity("Endure.Data.Models.ClimateDevice", b =>
                {
                    b.HasOne("Endure.Data.Models.StorageUnit", "StorageUnit")
                        .WithMany("ClimateDevices")
                        .HasForeignKey("StorageUnitId");

                    b.Navigation("StorageUnit");
                });

            modelBuilder.Entity("Endure.Data.Models.ClimateTelemetry", b =>
                {
                    b.HasOne("Endure.Data.Models.ClimateDevice", "ClimateDevice")
                        .WithMany("ClimateTelemetry")
                        .HasForeignKey("ClimateDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClimateDevice");
                });

            modelBuilder.Entity("Endure.Data.Models.ProductBatch", b =>
                {
                    b.HasOne("Endure.Data.Models.Product", "Product")
                        .WithMany("ProductBatches")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Endure.Data.Models.StorageUnit", "StorageUnit")
                        .WithMany("Products")
                        .HasForeignKey("StorageUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("StorageUnit");
                });

            modelBuilder.Entity("Endure.Data.Models.StorageUnit", b =>
                {
                    b.HasOne("Endure.Data.Models.StorageUnit", "ParentStorageUnit")
                        .WithMany("ChildStorageUnits")
                        .HasForeignKey("ParentStorageUnitId");

                    b.HasOne("Endure.Data.Models.Warehouse", "Warehouse")
                        .WithMany("StorageUnits")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentStorageUnit");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Endure.Data.Models.Warehouse", b =>
                {
                    b.HasOne("Endure.Data.Models.Warehouse", "ParentWarehouse")
                        .WithMany("ChildWarehouse")
                        .HasForeignKey("ParentWarehouseId");

                    b.Navigation("ParentWarehouse");
                });

            modelBuilder.Entity("Endure.Data.Models.ClimateDevice", b =>
                {
                    b.Navigation("ClimateTelemetry");
                });

            modelBuilder.Entity("Endure.Data.Models.Product", b =>
                {
                    b.Navigation("ProductBatches");
                });

            modelBuilder.Entity("Endure.Data.Models.StorageUnit", b =>
                {
                    b.Navigation("ChildStorageUnits");

                    b.Navigation("ClimateDevices");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Endure.Data.Models.Warehouse", b =>
                {
                    b.Navigation("ChildWarehouse");

                    b.Navigation("StorageUnits");
                });
#pragma warning restore 612, 618
        }
    }
}
