// <auto-generated />
using System;
using Endure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Endure.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Endure.Data.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Log")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LogLevel")
                        .HasColumnType("integer");

                    b.Property<int>("ModuleType")
                        .HasColumnType("integer");

                    b.Property<string>("RequestId")
                        .HasColumnType("text");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("bigint");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("Endure.Data.Models.ClimateDevice", b =>
                {
                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsConnected")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<long>("LastReceived")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("StorageUnitId")
                        .HasColumnType("uuid");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("bigint");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("WarehouseId", "Id");

                    b.HasIndex("WarehouseId", "StorageUnitId");

                    b.ToTable("ClimateDevice");
                });

            modelBuilder.Entity("Endure.Data.Models.ClimateTelemetry", b =>
                {
                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClimateDeviceId")
                        .HasColumnType("uuid");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<double?>("Humidity")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<double?>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("bigint");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("WarehouseId", "Id");

                    b.ToTable("ClimateTelemetry");
                });

            modelBuilder.Entity("Endure.Data.Models.DietaryRestriction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<Guid>("DietaryRestrictionTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("HashedCpr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("bigint");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DietaryRestrictionTypeId");

                    b.ToTable("DietaryRestriction");
                });

            modelBuilder.Entity("Endure.Data.Models.DietaryRestrictionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("bigint");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("DietaryRestrictionType");
                });

            modelBuilder.Entity("Endure.Data.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("bigint");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Endure.Data.Models.ProductBatch", b =>
                {
                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long>("BestBefore")
                        .HasColumnType("bigint");

                    b.Property<long>("Count")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("StorageUnitId")
                        .HasColumnType("uuid");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("bigint");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("WarehouseId", "Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("WarehouseId", "StorageUnitId");

                    b.ToTable("ProductBatch");
                });

            modelBuilder.Entity("Endure.Data.Models.StorageUnit", b =>
                {
                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSlot")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentStorageUnitId")
                        .HasColumnType("uuid");

                    b.Property<string>("ShortName")
                        .HasColumnType("text");

                    b.Property<int>("StorageType")
                        .HasColumnType("integer");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("bigint");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("WarehouseId", "Id");

                    b.HasIndex("WarehouseId", "ParentStorageUnitId");

                    b.ToTable("StorageUnit");
                });

            modelBuilder.Entity("Endure.Data.Models.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRoot")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentWarehouseId")
                        .HasColumnType("uuid");

                    b.Property<string>("ShortName")
                        .HasColumnType("text");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("bigint");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ParentWarehouseId");

                    b.ToTable("Warehouse");
                });

            modelBuilder.Entity("Endure.Data.Models.ClimateDevice", b =>
                {
                    b.HasOne("Endure.Data.Models.StorageUnit", "StorageUnit")
                        .WithMany("ClimateDevices")
                        .HasForeignKey("WarehouseId", "StorageUnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("StorageUnit");
                });

            modelBuilder.Entity("Endure.Data.Models.ClimateTelemetry", b =>
                {
                    b.HasOne("Endure.Data.Models.ClimateDevice", "ClimateDevice")
                        .WithMany("ClimateTelemetry")
                        .HasForeignKey("WarehouseId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClimateDevice");
                });

            modelBuilder.Entity("Endure.Data.Models.DietaryRestriction", b =>
                {
                    b.HasOne("Endure.Data.Models.DietaryRestrictionType", "DietaryRestrictionType")
                        .WithMany("DietaryRestrictions")
                        .HasForeignKey("DietaryRestrictionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DietaryRestrictionType");
                });

            modelBuilder.Entity("Endure.Data.Models.ProductBatch", b =>
                {
                    b.HasOne("Endure.Data.Models.Product", "Product")
                        .WithMany("ProductBatches")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Endure.Data.Models.StorageUnit", "StorageUnit")
                        .WithMany("Products")
                        .HasForeignKey("WarehouseId", "StorageUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("StorageUnit");
                });

            modelBuilder.Entity("Endure.Data.Models.StorageUnit", b =>
                {
                    b.HasOne("Endure.Data.Models.Warehouse", "Warehouse")
                        .WithMany("StorageUnits")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Endure.Data.Models.StorageUnit", "ParentStorageUnit")
                        .WithMany("ChildStorageUnits")
                        .HasForeignKey("WarehouseId", "ParentStorageUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentStorageUnit");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Endure.Data.Models.Warehouse", b =>
                {
                    b.HasOne("Endure.Data.Models.Warehouse", "ParentWarehouse")
                        .WithMany("ChildWarehouses")
                        .HasForeignKey("ParentWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentWarehouse");
                });

            modelBuilder.Entity("Endure.Data.Models.ClimateDevice", b =>
                {
                    b.Navigation("ClimateTelemetry");
                });

            modelBuilder.Entity("Endure.Data.Models.DietaryRestrictionType", b =>
                {
                    b.Navigation("DietaryRestrictions");
                });

            modelBuilder.Entity("Endure.Data.Models.Product", b =>
                {
                    b.Navigation("ProductBatches");
                });

            modelBuilder.Entity("Endure.Data.Models.StorageUnit", b =>
                {
                    b.Navigation("ChildStorageUnits");

                    b.Navigation("ClimateDevices");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Endure.Data.Models.Warehouse", b =>
                {
                    b.Navigation("ChildWarehouses");

                    b.Navigation("StorageUnits");
                });
#pragma warning restore 612, 618
        }
    }
}
