name: Endure

services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: endure
      POSTGRES_USER: endure
      POSTGRES_PASSWORD: endure
    volumes:
      - postgres:/var/lib/postgresql/18/docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U endure -d endure -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
 
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: passw0rd
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
  
  rabbitmq:
    image: rabbitmq:4.2.5
    environment:
      RABBITMQ_DEFAULT_USER: endure
      RABBITMQ_DEFAULT_PASS: endure
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq
      - rabbitmq-log:/var/log/rabbitmq
    ports:
      - "5672:5672"     # AMQP protocol
      - "15672:15672"   # Management UI
      - "1883:1883"     # MQTT protocol
     
configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management,rabbitmq_mqtt]."  

volumes:
  postgres:
  pgadmin:
  rabbitmq-lib:
  rabbitmq-log: